### ISSUE TITLE
memory leak when strict_decoding is enabled

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#1006]
Hello,

I am using strict_decoding and I received following report from fuzzer:

```
heif_decode_image error: Invalid input: Unknown NCLX matrix coefficients: Unknown error

=================================================================
==222987==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x576a3d in operator new(unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x5942da in heif_image_create libheif/libheif/heif.cc:1085:28
    #2 0x6fe473 in convert_libde265_image_to_heif_image libheif/libheif/plugins/decoder_libde265.cc:95:9
    #3 0x6fe473 in libde265_v1_decode_image(void*, heif_image**) libheif/libheif/plugins/decoder_libde265.cc:334:13
    #4 0x5e08d7 in HeifContext::decode_image_planar(unsigned int, std::__1::shared_ptr<HeifPixelImage>&, heif_colorspace, heif_decoding_options const&, bool) const libheif/libheif/context.cc:1355:11
    #5 0x5dd3c6 in HeifContext::decode_image_user(unsigned int, std::__1::shared_ptr<HeifPixelImage>&, heif_colorspace, heif_chroma, heif_decoding_options const&) const libheif/libheif/context.cc:1248:15
    #6 0x5938cf in heif_decode_image libheif/libheif/heif.cc:1046:35
    #7 0x57f87f in HEIFHandler::ensureDecoder() /src/kimageformats/src/imageformats/heif.cpp:501:11
    #8 0x579fc4 in ensureParsed /src/kimageformats/src/imageformats/heif.cpp:410:26
    #9 0x579fc4 in HEIFHandler::read(QImage*) /src/kimageformats/src/imageformats/heif.cpp:75:10
    #10 0x57935c in LLVMFuzzerTestOneInput /src/kimgio_fuzzer.cc:62:14
    #11 0x44aa63 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #12 0x4361c2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #13 0x43ba6c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #14 0x464fa2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #15 0x7ea6604c2082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
```

I think the problem is here:

https://github.com/strukturag/libheif/blob/49bd673c5110ebd56f0067b761489f4a5a75950d/libheif/plugins/decoder_libde265.cc#L341C7-L341C24

I think that HEIF_WARN_OR_FAIL cleanupBlock should probably call `heif_image_release` too.

**Comment by farindk** [comment]
Right. Does it work correctly with the above change?

**Comment by novomesk** [comment]
Yes, it works, thanks!
