### ISSUE TITLE
Direct-leak in aom_new_decoder 

### ISSUE THREAD

**Issue by bobfriesenhahn** [strukturag/libheif#1326]
In GraphicsMagick oss-fuzz testing, this new issue (a memory leak) is reported.  The backtrace looks like this:

```
Direct leak of 80 byte(s) in 1 object(s) allocated from:
	    #0 0x5ca7d9a4687d in operator new(unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:86:3
	    #1 0x5ca7da1bcdcd in aom_new_decoder(void**) [libheif/libheif/plugins/decoder_aom.cc:88](https://github.com/strukturag/libheif/blob/0b3b41534624ded34184105d105fcffb4c2fb944/libheif/plugins/decoder_aom.cc#L88):33
	    #2 0x5ca7da16ac4e in Decoder::decode_single_frame_from_compressed_data(heif_decoding_options const&) [libheif/libheif/codecs/decoder.cc:179](https://github.com/strukturag/libheif/blob/0b3b41534624ded34184105d105fcffb4c2fb944/libheif/codecs/decoder.cc#L179):27
	    #3 0x5ca7d9ff798a in ImageItem::decode_compressed_image(heif_decoding_options const&, bool, unsigned int, unsigned int) const [libheif/libheif/image-items/image_item.cc:978](https://github.com/strukturag/libheif/blob/0b3b41534624ded34184105d105fcffb4c2fb944/libheif/image-items/image_item.cc#L978):19
	    #4 0x5ca7d9ff04aa in ImageItem::decode_image(heif_decoding_options const&, bool, unsigned int, unsigned int) const [libheif/libheif/image-items/image_item.cc:745](https://github.com/strukturag/libheif/blob/0b3b41534624ded34184105d105fcffb4c2fb944/libheif/image-items/image_item.cc#L745):60
	    #5 0x5ca7da1016c5 in HeifContext::decode_image(unsigned int, heif_colorspace, heif_chroma, heif_decoding_options const&, bool, unsigned int, unsigned int) const [libheif/libheif/context.cc:989](https://github.com/strukturag/libheif/blob/0b3b41534624ded34184105d105fcffb4c2fb944/libheif/context.cc#L989):34
	    #6 0x5ca7d9fb091a in heif_decode_image [libheif/libheif/api/libheif/heif.cc:1320](https://github.com/strukturag/libheif/blob/0b3b41534624ded34184105d105fcffb4c2fb944/libheif/api/libheif/heif.cc#L1320):80
	    #7 0x5ca7d9d02155 in ReadHEIFImage /src/graphicsmagick/coders/heif.c:667:15
	    #8 0x5ca7d9b1253c in ReadImage /src/graphicsmagick/magick/constitute.c:1682:13
	    #9 0x5ca7d9ac4164 in BlobToImage /src/graphicsmagick/magick/blob.c:785:13
	    #10 0x5ca7d9a542b2 in Magick::Image::read(Magick::Blob const&) /src/graphicsmagick/Magick++/lib/Image.cpp:1592:5
	    #11 0x5ca7d9a4902d in LLVMFuzzerTestOneInput /src/graphicsmagick/fuzzing/coder_fuzzer.cc:24:11
	    #12 0x5ca7d98fd6e0 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
	    #13 0x5ca7d98e8955 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:327:6
	    #14 0x5ca7d98ee3ef in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:862:9
	    #15 0x5ca7d9919692 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
	    #16 0x7b7c493c0082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/libc-start.c:308:16
```

This is the input file which provokes the issue (.jpg extension added to defeat github):

![clusterfuzz-testcase-minimized-coder_HEIC_fuzzer-5727314899435520 avif](https://github.com/user-attachments/assets/b19c0a84-045b-467d-8b2a-913cc9948405)

**Comment by farindk** [comment]
Could it be that this is already fixed by https://github.com/strukturag/libheif/pull/1324 ?

**Comment by bobfriesenhahn** [comment]
After a successful build and fuzz test, oss-fuzz issue [371659892](https://issues.oss-fuzz.com/issues/371659892) is closed.
