### ISSUE TITLE
Problem decoding JPEG 2000 image

### ISSUE THREAD

**Issue by bradh** [strukturag/libheif#1348]
I've hit a problem decoding a JPEG-2000 image item which is created by `heif-enc`.

The test environment is Kubuntu 24.04, building master branch, with only the CMakeLists.txt change for OpenJPEG detection.

```
bradh@audax:~/coding/libheif/build$ ./examples/heif-enc --jpeg2000 ~/mini_samples/complex_osm_tile.png -o j2k.hif
bradh@audax:~/coding/libheif/build$ ./examples/heif-dec j2k.hif
File contains 1 image
heif-dec: /home/bradh/coding/libheif/libheif/codecs/decoder.cc:66: Result<std::vector<unsigned char>*> DataExtent::read_data() const: Assertion `false' failed.
Aborted (core dumped)
```

The backtrace looks like this:
```
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimised out>) at ./nptl/pthread_kill.c:44
warning: 44     ./nptl/pthread_kill.c: No such file or directory
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimised out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimised out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimised out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6e4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6e288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff6e2881b in __assert_fail_base
    (fmt=0x7ffff6fd01e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff7d1a8e4 "false", file=file@entry=0x7ffff7d1a8a8 "/home/bradh/coding/libheif/libheif/codecs/decoder.cc", line=line@entry=66, function=function@entry=0x7ffff7d1a860 "Result<std::vector<unsigned char>*> DataExtent::read_data() const") at ./assert/assert.c:94
#6  0x00007ffff6e3b507 in __assert_fail (assertion=0x7ffff7d1a8e4 "false", file=0x7ffff7d1a8a8 "/home/bradh/coding/libheif/libheif/codecs/decoder.cc", line=66, function=0x7ffff7d1a860 "Result<std::vector<unsigned char>*> DataExtent::read_data() const") at ./assert/assert.c:103
#7  0x00007ffff7829e89 in DataExtent::read_data (this=0x555555597798) at /home/bradh/coding/libheif/libheif/codecs/decoder.cc:66
#8  0x00007ffff782aa23 in Decoder::get_compressed_data (this=0x555555597790) at /home/bradh/coding/libheif/libheif/codecs/decoder.cc:157
#9  0x00007ffff7842b48 in Decoder_JPEG2000::get_luma_bits_per_pixel (this=0x555555597790) at /home/bradh/coding/libheif/libheif/codecs/jpeg2000_dec.cc:37
#10 0x00007ffff785b479 in ImageItem::get_luma_bits_per_pixel (this=0x55555559ad50) at /home/bradh/coding/libheif/libheif/image-items/image_item.cc:483
#11 0x00007ffff78057c1 in heif_image_handle_get_luma_bits_per_pixel (handle=0x5555555975a0) at /home/bradh/coding/libheif/libheif/api/libheif/heif.cc:1202
#12 0x0000555555559669 in decode_single_image (handle=0x5555555975a0, filename_stem="j2k", filename_suffix="jpg", decode_options=0x55555559afc0, encoder=std::unique_ptr<Encoder> = {...}) at /home/bradh/coding/libheif/examples/heif_dec.cc:232
#13 0x000055555555c655 in main (argc=2, argv=0x7fffffffdb38) at /home/bradh/coding/libheif/examples/heif_dec.cc:872
```

The problem is that the extent has `m_source` value of 0 (i.e. raw, not sequence).

I can't see how that can occur though. It looks like the value is being set OK.

**Comment by farindk** [comment]
Found it. Apparently a refactoring typo. Thanks.
