### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#1404]
Hello,

This file from fuzzer crashes heif-dec on my system.

[testfile.zip](https://github.com/user-attachments/files/17842569/testfile.zip)

```
heif-dec clusterfuzz-testcase-kimgio_heif_fuzzer-6210752350846976 output.png
File contains 1 image
Fatal glibc error: malloc.c:2599 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)
Aborted
```

```
#0  0x00007ffff78c037c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff786e966 in raise () from /lib64/libc.so.6
#2  0x00007ffff78568f7 in abort () from /lib64/libc.so.6
#3  0x00007ffff785796f in __libc_message_impl.cold () from /lib64/libc.so.6
#4  0x00007ffff7866d97 in __libc_assert_fail () from /lib64/libc.so.6
#5  0x00007ffff78cd32e in sysmalloc () from /lib64/libc.so.6
#6  0x00007ffff78ce2c8 in _int_malloc () from /lib64/libc.so.6
#7  0x00007ffff78cec0d in malloc () from /lib64/libc.so.6
#8  0x00007ffff7ab34fc in operator new (sz=15887)
    at /var/tmp/portage/sys-devel/gcc-13.3.1_p20241025/work/gcc-13-20241025/libstdc++-v3/libsupc++/new_op.cc:50
#9  0x00007ffff7e8e480 in HeifPixelImage::ImagePlane::alloc(unsigned int, unsigned int, heif_channel_datatype, int, int, heif_security_limits const*)
    () from /usr/lib64/libheif.so.1
#10 0x00007ffff7e90618 in HeifPixelImage::add_plane(heif_channel, unsigned int, unsigned int, int, heif_security_limits const*) ()
   from /usr/lib64/libheif.so.1
#11 0x00007ffff7f2ad8d in Op_to_sdr_planes::convert_colorspace(std::shared_ptr<HeifPixelImage const> const&, ColorState const&, ColorState const&, heif_color_conversion_options const&, heif_security_limits const*) const () from /usr/lib64/libheif.so.1
#12 0x00007ffff7f103e4 in ColorConversionPipeline::convert_image(std::shared_ptr<HeifPixelImage> const&, heif_security_limits const*) ()
   from /usr/lib64/libheif.so.1
#13 0x00007ffff7f12ef7 in convert_colorspace(std::shared_ptr<HeifPixelImage> const&, heif_colorspace, heif_chroma, std::shared_ptr<color_profile_nclx const> const&, int, heif_color_conversion_options const&, heif_security_limits const*) () from /usr/lib64/libheif.so.1
#14 0x00007ffff7e73264 in HeifContext::decode_image(unsigned int, heif_colorspace, heif_chroma, heif_decoding_options const&, bool, unsigned int, unsigned int) const () from /usr/lib64/libheif.so.1
#15 0x00007ffff7ea436c in heif_decode_image () from /usr/lib64/libheif.so.1
#16 0x000055555555b8d9 in decode_single_image(heif_image_handle*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, heif_decoding_options*, std::unique_ptr<Encoder, std::default_delete<Encoder> >&) ()
#17 0x000055555555a4a5 in main ()
```

**Comment by farindk** [comment]
Thanks. This happened when the alpha plane was 8 bit, but the color planes >8 bit.
