### ISSUE TITLE
Direct-leak in NAL_Parser::alloc_NAL_unit (oss-fuzz issue 382930446)

### ISSUE THREAD

**Issue by bobfriesenhahn** [strukturag/libheif#1430]
GraphicsMagick now includes many/most of the libheif dependencies in its oss-fuzz build configuration.

Oss-fuzz has detected a memory leak which I suspect is the responsibility of libheif, although it seems that libheif code intended to avoid it.  I am able to reproduce this leak outside of the oss-fuzz build and valgrind reports similar information to the oss-fuzz stack trace.

The oss-fuzz issue is at [382930446382930446](https://issues.oss-fuzz.com/issues/382930446) and this is the oss-fuzz stack trace:

```
Direct leak of 64 byte(s) in 1 object(s) allocated from:
	    #0 0x5c6131e0224d in operator new(unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:86:3
	    #1 0x5c61326327d6 in NAL_Parser::alloc_NAL_unit(int) [libde265/libde265/nal-parser.cc:201](https://github.com/strukturag/libde265/blob/62a8ae58dbd4a9f9d711d8807ac35fdc4dd509b6/libde265/nal-parser.cc#L201):11
	    #2 0x5c6132634232 in NAL_Parser::push_NAL(unsigned char const*, int, long, void*) [libde265/libde265/nal-parser.cc:379](https://github.com/strukturag/libde265/blob/62a8ae58dbd4a9f9d711d8807ac35fdc4dd509b6/libde265/nal-parser.cc#L379):19
	    #3 0x5c61325d03ce in libde265_v1_push_data(void*, void const*, unsigned long) [libheif/libheif/plugins/decoder_libde265.cc:294](https://github.com/strukturag/libheif/blob/8788273245d8a1a995fa88a7230794c3de028e7c/libheif/plugins/decoder_libde265.cc#L294):5
	    #4 0x5c61325723fe in Decoder::decode_single_frame_from_compressed_data(heif_decoding_options const&) [libheif/libheif/codecs/decoder.cc:208](https://github.com/strukturag/libheif/blob/8788273245d8a1a995fa88a7230794c3de028e7c/libheif/codecs/decoder.cc#L208):9
	    #5 0x5c613238fb7a in ImageItem::decode_compressed_image(heif_decoding_options const&, bool, unsigned int, unsigned int) const [libheif/libheif/image-items/image_item.cc:1016](https://github.com/strukturag/libheif/blob/8788273245d8a1a995fa88a7230794c3de028e7c/libheif/image-items/image_item.cc#L1016):19
	    #6 0x5c613238a682 in ImageItem::decode_image(heif_decoding_options const&, bool, unsigned int, unsigned int) const [libheif/libheif/image-items/image_item.cc:779](https://github.com/strukturag/libheif/blob/8788273245d8a1a995fa88a7230794c3de028e7c/libheif/image-items/image_item.cc#L779):60
	    #7 0x5c61324f9b91 in HeifContext::decode_image(unsigned int, heif_colorspace, heif_chroma, heif_decoding_options const&, bool, unsigned int, unsigned int) const [libheif/libheif/context.cc:1069](https://github.com/strukturag/libheif/blob/8788273245d8a1a995fa88a7230794c3de028e7c/libheif/context.cc#L1069):34
	    #8 0x5c6132346548 in heif_decode_image [libheif/libheif/api/libheif/heif.cc:1437](https://github.com/strukturag/libheif/blob/8788273245d8a1a995fa88a7230794c3de028e7c/libheif/api/libheif/heif.cc#L1437):80
	    #9 0x5c61320b2966 in ReadHEIFImage /src/graphicsmagick/coders/heif.c:675:15
	    #10 0x5c6131ece33c in ReadImage /src/graphicsmagick/magick/constitute.c:1682:13
	    #11 0x5c6131e7ff64 in BlobToImage /src/graphicsmagick/magick/blob.c:785:13
	    #12 0x5c6131e100a2 in Magick::Image::read(Magick::Blob const&) /src/graphicsmagick/Magick++/lib/Image.cpp:1592:5
	    #13 0x5c6131e049fd in LLVMFuzzerTestOneInput /src/graphicsmagick/fuzzing/coder_fuzzer.cc:24:11
	    #14 0x5c6131cb90b0 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
	    #15 0x5c6131ca4325 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:327:6
	    #16 0x5c6131ca9dbf in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:862:9
	    #17 0x5c6131cd5062 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
	    #18 0x783dc5453082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/libc-start.c:308:16
```
while I see this stack trace from valgrind:

```
==1201617== 157 (64 direct, 93 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 6
==1201617==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1201617==    by 0x5CA9211: NAL_Parser::alloc_NAL_unit(int) (nal-parser.cc:201)
==1201617==    by 0x5CA9546: NAL_Parser::push_NAL(unsigned char const*, int, long, void*) (nal-parser.cc:379)
==1201617==    by 0x49D9401: libde265_v1_push_data(void*, void const*, unsigned long) (in /usr/local/lib/libheif.so.1.19.5)
==1201617==    by 0x495CB8F: Decoder::decode_single_frame_from_compressed_data(heif_decoding_options const&) (in /usr/local/lib/libheif.so.1.19.5)
==1201617==    by 0x4988199: ImageItem::decode_compressed_image(heif_decoding_options const&, bool, unsigned int, unsigned int) const (in /usr/local/lib/libheif.so.1.19.5)
==1201617==    by 0x498A0F7: ImageItem::decode_image(heif_decoding_options const&, bool, unsigned int, unsigned int) const (in /usr/local/lib/libheif.so.1.19.5)
==1201617==    by 0x4914357: HeifContext::decode_image(unsigned int, heif_colorspace, heif_chroma, heif_decoding_options const&, bool, unsigned int, unsigned int) const (in /usr/local/lib/libheif.so.1.19.5)
==1201617==    by 0x494D334: heif_decode_image (in /usr/local/lib/libheif.so.1.19.5)
==1201617==    by 0x234E6B: ReadHEIFImage (heif.c:675)
==1201617==    by 0x151D42: ReadImage (constitute.c:1682)
==1201617==    by 0x134E69: ConvertImageCommand (command.c:4541)
==1201617== 
```

This is the file to produce the issue:

![clusterfuzz-testcase-minimized-coder_HEIF_fuzzer-6192231632928768 heif](https://github.com/user-attachments/assets/6228c204-aa88-4d44-80ba-f078b276a488)

**Comment by farindk** [comment]
I fixed it in this libde265 commit: https://github.com/strukturag/libde265/commit/f699d4dc9121f3e5d2099c291b29d4efc90ca5fb

**Comment by bobfriesenhahn** [comment]
Oss-fuzz has apparently not detected this leak since December 20th, but it has not closed the issue yet either.  It seems that the leak is/was somewhat "ambiguous" since it did not occur on every test run and so oss-fuzz is challenged to decide that the issue is fixed.

With updated libde265, I am no longer able to provoke a memory leak report using valgrind.

**Comment by bobfriesenhahn** [comment]
Oss-fuzz has finally agreed that this issue is fixed.
