### ISSUE TITLE
resize heic file exception

### ISSUE THREAD

**Issue by lzzcg** [strukturag/libheif#41]
please refer to the issue [https://github.com/ImageMagick/ImageMagick/issues/1173](url)

when I resize a heic file by imagemagick, I got an error as below:
suse11sp1:~/lzz # convert -resize 120x120 20171218_IMG_0449.HEIC 20171218_IMG_0449.jpg terminate called after throwing an instance of 'std::system_error' what(): Resource temporarily unavailable Aborted

and I find that the error is related to the heic file size.
when the file size is 1.4M, I can resize the file right.
but when the file size is 5.5M, I got the errors.

`suse11sp1:~/lzz # ll -h
total 30M
-rw-r--r-- 1 root root 1.4M Dec 18 08:41 20171218_IMG_0446.HEIC
-rw-r--r-- 1 root root 5.5M Dec 18 08:41 20171218_IMG_0449.HEIC
-rw-r--r-- 1 root root 595K Dec 18 08:41 20171218_IMG_0455.HEIC
-rw-r--r-- 1 root root 66K Jun 14 06:01 20171218_IMG_0455.jpg

suse11sp1:/lzz # convert -resize 120x120 20171218_IMG_0446.HEIC 20171218_IMG_0446.jpg
suse11sp1:/lzz # convert -resize 120x120 20171218_IMG_0449.HEIC 20171218_IMG_0449.jpg
terminate called after throwing an instance of 'std::system_error'
what(): Resource temporarily unavailable
Aborted`

**Comment by farindk** [comment]
Most likely a problem with your file-system. libheif does not access the files directly, it just uses the memory buffer it gets from ImageMagick.

However, if you attach your file here, I will try it on my system.

**Comment by lzzcg** [comment]
Hi  farindk，

I cannot upload the file in my proxy policy， I'm wondering whether you could provide an email address so that I can attach the file to the email.

thank you in advance :)

By the way. below is the gdb debug info from my system, hope it helps.

terminate called after throwing an instance of 'std::system_error'
what(): Resource temporarily unavailable

Program received signal SIGABRT, Aborted.
0x00007ffff5702f59 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56 return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0 0x00007ffff5702f59 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1 0x00007ffff5704358 in __GI_abort () at abort.c:90
#2 0x00007ffff6410445 in __gnu_cxx::__verbose_terminate_handler () at ../../../../gcc-4.8.1/libstdc++-v3/libsupc++/vterminate.cc:95
#3 0x00007ffff640e5b6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../gcc-4.8.1/libstdc++-v3/libsupc++/eh_terminate.cc:38
#4 0x00007ffff640e5e3 in std::terminate () at ../../../../gcc-4.8.1/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5 0x00007ffff640e856 in __cxxabiv1::__cxa_rethrow () at ../../../../gcc-4.8.1/libstdc++-v3/libsupc++/eh_throw.cc:122
#6 0x00007ffff6be35e1 in __shared_count<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)>, heif::Error>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)>, heif::Error> >, std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)> > (__a=..., this=<optimized out>) at /usr/local/include/c++/4.8.1/bits/shared_ptr_base.h:529
#7 __shared_ptr<std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)>, heif::Error> >, std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)> > (__a=..., __tag=..., this=<optimized out>)
at /usr/local/include/c++/4.8.1/bits/shared_ptr_base.h:986
#8 shared_ptr<std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)>, heif::Error> >, std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)> > (__a=..., __tag=..., this=<optimized out>)
at /usr/local/include/c++/4.8.1/bits/shared_ptr.h:316
#9 allocate_shared<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)>, heif::Error>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)>, heif::Error> >, std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)> > (
__a=...) at /usr/local/include/c++/4.8.1/bits/shared_ptr.h:598
#10 make_shared<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)>, heif::Error>, std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)> > () at /usr/local/include/c++/4.8.1/bits/shared_ptr.h:614
#11 _S_make_async_state<std::_Bind_simple<std::_Mem_fn<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)const>(const heif::HeifContext*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int)> > (__fn=<optimized out>) at /usr/local/include/c++/4.8.1/future:1511
#12 std::async<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int) const, heif::HeifContext const* const, unsigned int&, std::shared_ptr<heif::HeifPixelImage>&, int&, int&>(std::launch, heif::Error (heif::HeifContext::*&&)(unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int) const, heif::HeifContext const* const&&, unsigned int&, std::shared_ptr<heif::HeifPixelImage>&, int&, int&) (__policy=__policy@entry=std::async, __fn=__fn@entry=<unknown type in /usr/local/lib/libheif.so.1, CU 0x166e5b, DIE 0x1c45fe>) at /usr/local/include/c++/4.8.1/future:1524
#13 0x00007ffff6bde3dd in heif::HeifContext::decode_full_grid_image (this=this@entry=0x62f528, ID=<optimized out>, img=..., grid_data=...) at heif_context.cc:1015
#14 0x00007ffff6bdf457 in heif::HeifContext::decode_image (this=0x62f528, ID=257, img=..., options=options@entry=0x0) at heif_context.cc:810
#15 0x00007ffff6bdfef1 in heif::HeifContext::Image::decode_image (this=<optimized out>, img=..., colorspace=colorspace@entry=heif_colorspace_YCbCr, chroma=chroma@entry=heif_chroma_420,
options=options@entry=0x0) at heif_context.cc:716
#16 0x00007ffff6bd6da0 in heif_decode_image (in_handle=0x630d00, out_img=out_img@entry=0x7fffffff4cc0, colorspace=colorspace@entry=heif_colorspace_YCbCr, chroma=chroma@entry=heif_chroma_420,
options=options@entry=0x0) at heif.cc:443
#17 0x00007ffff7a66d1f in ReadHEICImage (image_info=0x61ad10, exception=0x612590) at coders/heic.c:267
#18 0x00007ffff787d75d in ReadImage (image_info=image_info@entry=0x617a20, exception=exception@entry=0x612590) at MagickCore/constitute.c:558
#19 0x00007ffff787e73c in ReadImages (image_info=0x612710, filename=0x611d20 "a.heic", exception=0x612590) at MagickCore/constitute.c:870
#20 0x00007ffff75aec9a in CLINoImageOperator (cli_wand=cli_wand@entry=0x616520, option=option@entry=0x7ffff75c8220 "-read", arg1n=arg1n@entry=0x7fffffffe76b "a.heic", arg2n=arg2n@entry=0x0)
at MagickWand/operation.c:4726
#21 0x00007ffff75afc59 in CLIOption (cli_wand=cli_wand@entry=0x616520, option=option@entry=0x7ffff75c8220 "-read") at MagickWand/operation.c:5221
#22 0x00007ffff7543e8d in ProcessCommandOptions (cli_wand=cli_wand@entry=0x616520, argc=argc@entry=3, argv=argv@entry=0x7fffffffe418, index=index@entry=1) at MagickWand/magick-cli.c:424
#23 0x00007ffff75448db in MagickImageCommand (image_info=0x612710, argc=3, argv=0x7fffffffe418, metadata=0x7fffffffc0e0, exception=0x612590) at MagickWand/magick-cli.c:796
#24 0x00007ffff755f34c in MagickCommandGenesis (image_info=image_info@entry=0x612710, command=command@entry=0x400f94 <MagickImageCommand@plt>, argc=argc@entry=3, argv=argv@entry=0x7fffffffe418,
metadata=0x0, exception=exception@entry=0x612590) at MagickWand/mogrify.c:183
#25 0x000000000040135f in MagickMain (argc=3, argv=0x7fffffffe418) at utilities/magick.c:149
#26 0x00007ffff56ef7c5 in __libc_start_main (main=0x401440 <main>, argc=3, ubp_av=0x7fffffffe418, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe408)
at libc-start.c:258
#27 0x0000000000401149 in _start () at ../sysdeps/x86_64/start.S:123

**Comment by farindk** [comment]
You can send the picture to farin@struktur.de

Thanks for the gdb dump. Something related to multi-threading, not the file-system ...

**Comment by farindk** [comment]
It looks like you have hit your OS limit on parallel threads. libheif decodes all tiles in an image in parallel, that's probably why you run into this issue only for large images. I might have to limit the number of decoding threads in libheif.

**Comment by farindk** [comment]
I just changed libheif to only use a limited number of decoding threads.
Please try the current version v1.3.2. The problem should not occur anymore.
