### ISSUE TITLE
Abrt (8922)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#46]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8922 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
==1==ERROR: AddressSanitizer: ABRT on unknown address 0x000000000001 (pc 0x7f5904896428 bp 0x0000018f7ca0 sp 0x7ffc65bccdd8 T0)
--
  | SCARINESS: 10 (signal)
  | #0 0x7f5904896427 in gsignal /build/glibc-Cl5G7W/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
  | #1 0x7f5904898029 in abort /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:89
  | #2 0x7f590488ebd6 in __assert_fail_base /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:92
  | #3 0x7f590488ec81 in __assert_fail /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:101
  | #4 0xdc0e27 in heif::BitstreamRange::skip_without_advancing_file_pos(long) libheif/libheif/bitstream.cc:303:3
  | #5 0xdc323c in heif::BitstreamRange::skip_to_end_of_box() libheif/libheif/bitstream.h:171:27
  | #6 0xdc856b in heif::Box::read(heif::BitstreamRange&, std::__1::shared_ptr<heif::Box>*) libheif/libheif/box.cc:481:12
  | #7 0xdc9efd in heif::Box::read_children(heif::BitstreamRange&, int) libheif/libheif/box.cc:540:19
  | #8 0xdd67bd in heif::Box_iprp::parse(heif::BitstreamRange&) libheif/libheif/box.cc:1476:10
  | #9 0xdc8454 in heif::Box::read(heif::BitstreamRange&, std::__1::shared_ptr<heif::Box>*) libheif/libheif/box.cc:476:20
  | #10 0xdc9efd in heif::Box::read_children(heif::BitstreamRange&, int) libheif/libheif/box.cc:540:19
  | #11 0xdd626c in heif::Box_iinf::parse(heif::BitstreamRange&) libheif/libheif/box.cc:1457:10
  | #12 0xdc8454 in heif::Box::read(heif::BitstreamRange&, std::__1::shared_ptr<heif::Box>*) libheif/libheif/box.cc:476:20
  | #13 0xdc9efd in heif::Box::read_children(heif::BitstreamRange&, int) libheif/libheif/box.cc:540:19
  | #14 0xdcc183 in heif::Box_meta::parse(heif::BitstreamRange&) libheif/libheif/box.cc:714:10
  | #15 0xdc8454 in heif::Box::read(heif::BitstreamRange&, std::__1::shared_ptr<heif::Box>*) libheif/libheif/box.cc:476:20
  | #16 0xdfd67c in heif::HeifFile::parse_heif_file(heif::BitstreamRange&) libheif/libheif/heif_file.cc:166:19
  | #17 0xdfcbf8 in heif::HeifFile::read(std::__1::shared_ptr<heif::StreamReader>) libheif/libheif/heif_file.cc:82:17
  | #18 0xdfcf68 in heif::HeifFile::read_from_memory(void const*, unsigned long, bool) libheif/libheif/heif_file.cc:71:10
  | #19 0xd9e356 in heif::HeifContext::read_from_memory(void const*, unsigned long, bool) libheif/libheif/heif_context.cc:356:28
  | #20 0xd85d0d in heif_context_read_from_memory libheif/libheif/heif.cc:107:29
```

Links: https://github.com/strukturag/libheif/blob/e20e01294d25499c48f0befb4183ccfde9009d29/libheif/bitstream.cc#L303

Commit: 2706077d0fe4019e4555bebb46e98ff57b850e63
Testcase file: [clusterfuzz-testcase-minimized-encoder_heic_fuzzer-6193003164073984.zip](https://github.com/strukturag/libheif/files/2139079/clusterfuzz-testcase-minimized-encoder_heic_fuzzer-6193003164073984.zip)

**Comment by farindk** [comment]
Thanks for reporting this. Fixed in b196c9deb.
