### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#493]
This was discovered by oss-fuzz (tested [heif plugin](https://invent.kde.org/frameworks/kimageformats/-/blob/master/src/imageformats/heif.cpp) from kimageformats) and re-checked by valgrind (using heif-convert only).

http://188.121.162.14/libheif/leak-3332f16bbeb91fb698a6153c9474d68cb205e3cf.heic

```
==6833== 16,399 bytes in 1 blocks are definitely lost in loss record 2 of 2
==6833==    at 0x48395EF: operator new[](unsigned long) (vg_replace_malloc.c:443)
==6833==    by 0x48BDD8D: heif::HeifPixelImage::ImagePlane::alloc(int, int, int, heif_chroma) (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x48BF614: heif::HeifPixelImage::add_plane(heif_channel, int, int, int) (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x48BF795: heif::HeifPixelImage::copy_new_plane_from(std::shared_ptr<heif::HeifPixelImage const> const&, heif_channel, heif_channel) (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x48E30E8: Op_to_sdr_planes::convert_colorspace(std::shared_ptr<heif::HeifPixelImage const> const&, heif::ColorState, heif::ColorConversionOptions) (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x48E0400: heif::ColorConversionPipeline::convert_image(std::shared_ptr<heif::HeifPixelImage> const&) (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x48E8B35: heif::convert_colorspace(std::shared_ptr<heif::HeifPixelImage> const&, heif_colorspace, heif_chroma, std::shared_ptr<heif::color_profile_nclx const>, int) (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x48D9400: heif::HeifContext::decode_image_user(unsigned int, std::shared_ptr<heif::HeifPixelImage>&, heif_colorspace, heif_chroma, heif_decoding_options const*) const (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x48C5B58: heif_decode_image (in /usr/lib64/libheif.so.1.12.0)
==6833==    by 0x10BC81: main (in /usr/bin/heif-convert)
==6833==
==6833== LEAK SUMMARY:
==6833==    definitely lost: 16,399 bytes in 1 blocks
==6833==    indirectly lost: 0 bytes in 0 blocks
==6833==      possibly lost: 0 bytes in 0 blocks
```
```
==13==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16399 byte(s) in 1 object(s) allocated from:
    #0 0x558d1d in operator new[](unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:102:3
    #1 0x606197 in heif::HeifPixelImage::ImagePlane::alloc(int, int, int, heif_chroma) /src/libheif/libheif/heif_image.cc:211:21
    #2 0x605dc6 in heif::HeifPixelImage::add_plane(heif_channel, int, int, int) /src/libheif/libheif/heif_image.cc:164:13
    #3 0x608efa in heif::HeifPixelImage::copy_new_plane_from(std::__1::shared_ptr<heif::HeifPixelImage const> const&, heif_channel, heif_channel) /src/libheif/libheif/heif_image.cc:431:3
    #4 0x62e470 in Op_to_sdr_planes::convert_colorspace(std::__1::shared_ptr<heif::HeifPixelImage const> const&, heif::ColorState, heif::ColorConversionOptions) /src/libheif/libheif/heif_colorconversion.cc:2486:17
    #5 0x639895 in heif::ColorConversionPipeline::convert_image(std::__1::shared_ptr<heif::HeifPixelImage> const&) /src/libheif/libheif/heif_colorconversion.cc:3034:19
    #6 0x63a35f in heif::convert_colorspace(std::__1::shared_ptr<heif::HeifPixelImage> const&, heif_colorspace, heif_chroma, std::__1::shared_ptr<heif::color_profile_nclx const>, int) /src/libheif/libheif/heif_colorconversion.cc:3141:19
    #7 0x5ab079 in heif::HeifContext::decode_image_user(unsigned int, std::__1::shared_ptr<heif::HeifPixelImage>&, heif_colorspace, heif_chroma, heif_decoding_options const*) const /src/libheif/libheif/heif_context.cc:1034:11
    #8 0x578e12 in heif_decode_image /src/libheif/libheif/heif.cc:917:35
    #9 0x5663c4 in heif::ImageHandle::decode_image(heif_colorspace, heif_chroma, heif::ImageHandle::DecodingOptions const&) /usr/local/include/libheif/heif_cxx.h:737:23
    #10 0x561619 in HEIFHandler::ensureDecoder() /src/kimageformats/src/imageformats/heif.cpp:415:34
    #11 0x55c684 in HEIFHandler::ensureParsed() const /src/kimageformats/src/imageformats/heif.cpp:360:18
    #12 0x55c5cf in HEIFHandler::read(QImage*) /src/kimageformats/src/imageformats/heif.cpp:75:10
    #13 0x55b76e in LLVMFuzzerTestOneInput /src/kimgio_fuzzer.cc:57:14
    #14 0x460231 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #15 0x45f73a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:505:3
    #16 0x461447 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:745:19
    #17 0x461ff5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:883:5
    #18 0x45017b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:906:6
    #19 0x47a1b2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #20 0x7f99613ff83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

DEDUP_TOKEN: operator new[](unsigned long)--heif::HeifPixelImage::ImagePlane::alloc(int, int, int, heif_chroma)--heif::HeifPixelImage::add_plane(heif_channel, int, int, int)
SUMMARY: AddressSanitizer: 16399 byte(s) leaked in 1 allocation(s).
```

**Comment by farindk** [comment]
thank you
