### ISSUE TITLE
Possible leak in x265 while decoding 

### ISSUE THREAD

**Issue by pierrejoye** [strukturag/libheif#535]
Example code, relatively classic usage:

https://github.com/libgd/libgd/blob/master/src/gd_heif.c#L113

I can only reproduce using our test:

https://github.com/libgd/libgd/blob/master/tests/heif/heif_im2im.c#L36

which reads using heif_context_read_from_memory_without_copy.

I am not completely sure where the allocations (2x leak):

=================================================================
==31634==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2048 byte(s) in 2 object(s) allocated from:
    #0 0x7f049d924aa5 in posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0x10eaa5)
    #1 0x7f049c33eb47 in x265::x265_malloc(unsigned long) (/lib/x86_64-linux-gnu/libx265.so.179+0x45db47)

SUMMARY: AddressSanitizer: 2048 byte(s) leaked in 2 allocation(s).

I also attached the valgrind log (ran it too), but there may be a lot of false positive, or a lot of other issues in x265 ;-)

[vg_logfile.txt](https://github.com/strukturag/libheif/files/6980662/vg_logfile.txt)

**Comment by pierrejoye** [comment]
Same in encoding

=================================================================
==32711==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2048 byte(s) in 2 object(s) allocated from:
    #0 0x7f2f7c195aa5 in posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0x10eaa5)
    #1 0x7f2f7ab92b47 in x265::x265_malloc(unsigned long) (/lib/x86_64-linux-gnu/libx265.so.179+0x45db47)

SUMMARY: AddressSanitizer: 2048 byte(s) leaked in 2 allocation(s).

**Comment by pierrejoye** [comment]
Additional info, expected ;)

![image](https://user-images.githubusercontent.com/282408/130344872-570f6c0c-26a5-47ba-acf0-98c6783c0ac2.png)

libde265_free_decoder or other are never used.

What was the idea or design behind it? As it may matter less in CLI apps, it is absolutely critical to free them in server environments. Happy to work on a PR however I would need to know what was the idea here :)

**Comment by bradh** [comment]
@pierrejoye Are you still seeing this problem?
