### ISSUE TITLE
Assertion `bit_depth >= 1' failed.

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#781]
Hello,

My program is triggering assertion on this fuzzer file: 
[Assertion.zip](https://github.com/strukturag/libheif/files/10686623/Assertion.zip)

`/root/libheif/libheif/heif_image.cc:141: bool heif::HeifPixelImage::ImagePlane::alloc(int, int, int, heif_chroma): Assertion 'bit_depth >= 1' failed.`

Attempt to decode via `heif-convert` to PNG did not trigger the assertion.

```
#5  0x00007ffff43d7d18 in heif::HeifPixelImage::ImagePlane::alloc (this=this@entry=0x7fffffffd080, width=width@entry=101, height=height@entry=1, bit_depth=bit_depth@entry=0,
    chroma=heif_chroma_444) at /root/libheif/libheif/heif_image.cc:141
#6  0x00007ffff43d86d1 in heif::HeifPixelImage::add_plane (this=0x555555594d70, channel=channel@entry=heif_channel_R, width=width@entry=101, height=height@entry=1,
    bit_depth=bit_depth@entry=0) at /root/libheif/libheif/heif_image.cc:127
#7  0x00007ffff43cafc9 in heif::HeifContext::decode_full_grid_image (this=this@entry=0x55555557a0b0, ID=2,
    img=std::shared_ptr<heif::HeifPixelImage> (use count 1, weak count 1) = {...}, grid_data=std::vector of length 188, capacity 188 = {...})
    at /root/libheif/libheif/heif_context.cc:1576
#8  0x00007ffff43c91b8 in heif::HeifContext::decode_image_planar (this=0x55555557a0b0, ID=<optimized out>,
    img=std::shared_ptr<heif::HeifPixelImage> (use count 1, weak count 1) = {...}, out_colorspace=out_colorspace@entry=heif_colorspace_RGB,
    options=options@entry=0x555555594b50, alphaImage=false) at /root/libheif/libheif/heif_context.cc:1256
#9  0x00007ffff43ca215 in heif::HeifContext::decode_image_user (this=<optimized out>, ID=<optimized out>,
    img=std::shared_ptr<heif::HeifPixelImage> (use count 1, weak count 1) = {...}, out_colorspace=heif_colorspace_RGB, out_chroma=heif_chroma_interleaved_RRGGBB_LE,
    options=0x555555594b50) at /root/libheif/libheif/heif_context.cc:1096
#10 0x00007ffff43bf919 in heif_decode_image (in_handle=0x555555581760, out_img=0x7fffffffd730, colorspace=<optimized out>, chroma=<optimized out>, options=<optimized out>)
    at /root/libheif/libheif/heif.cc:958
```

**Comment by farindk** [comment]
The input `pixi` box had a bits-per-pixel value of 0.
I did not try to reproduce this with your input file, but the above change should now return an error instead of throwing the assertion.

**Comment by novomesk** [comment]
Thx!
Now my program prints:
`heif_decode_image error: Invalid input: Invalid pixi box: Invalid bits per pixel in pixi box.`

**Comment by farindk** [comment]
Ok, thanks for confirming the change.
Maybe not the prettiest error message text, but at least it's clear what is wrong with the input :-)
